### ISSUE TITLE
Will espresso support jetpack compose?

### ISSUE THREAD

**Issue by sanjeevirajm** [android/compose-samples#100]
Will espresso support jetpack compose UI once it became production ready?

Problems facing in compose and espresso integration now:

We are using view id and content description in espresso testing. unable to set id and content description in Jetpack compose
And the view hierarchy itself changed, unable to see child views of AndroidComposeView in layout inspector

**Comment by sanjeevirajm** [comment]
Got answer: 
https://github.com/android/compose-samples/commit/a6907c5dc236e9c18f062c44453b1c15359962cf

**Comment by YagnikYudiz** [comment]
> Will espresso support jetpack compose UI once it became production ready?
> 
> Problems facing in compose and espresso integration now:
> 
> We are using view id and content description in espresso testing. unable to set id and content description in Jetpack compose
> And the view hierarchy itself changed, unable to see child views of AndroidComposeView in layout inspector



> Will espresso support jetpack compose UI once it became production ready?
> 
> Problems facing in compose and espresso integration now:
> 
> We are using view id and content description in espresso testing. unable to set id and content description in Jetpack compose
> And the view hierarchy itself changed, unable to see child views of AndroidComposeView in layout inspector

Same Problem if anyone find any solution then please let me know by replaying this comment

**Comment by seadowg** [comment]
@nickbutcher @JoseAlcerreca this doesn't appear to be solved and the answer given in https://github.com/android/compose-samples/commit/a6907c5dc236e9c18f062c44453b1c15359962cf doesn't seem sufficient for applications mixing Compose and View (a legacy app introducing Compose for example). The example given (which is similar to that given in [the docs](https://developer.android.com/develop/ui/compose/testing/interoperability#interoperability_with_espresso)) accurately suggests that Compose views will not work with Espresso, but that you can still mix and match Espresso (presumably using `ActivityScenario` or `FragmentScenario`) in with a test that uses `ComposeTestRule`. In practice, I'm not sure how useful that would be however: you wouldn't be able to write an Espresso test for an Activity or a multi Activity flow if there was any Composables involved in the UI.

To illustrate this more concretely, imagine I was working on a legacy app using a single Activity/multi Fragment architecture with a login flow that I wanted to convert to Compose. I might have an existing (instrumented) UI test that uses Espresso and `ActivityScenario`:

```kotlin
ActivityScenario.launch(MainActivity::class.java).use {
    onView(withHint("Username")).perform(replaceText("seadowg"))
    onView(withHint("Password")).perform(replaceText("super secret"))

    onView(withText("Login")).perform(click())
    onView(withText("Welcome!")).check(matches(isDisplayed))
}
```

Let's assume we have two Fragments here: `LoginFragment` and `HomeFragment` (with the "Welcome!" message). I could then convert `LoginFragment` to use a Composable instead of a View (following the [documented example](https://developer.android.com/develop/ui/compose/migrate/strategy#build-new) from the migration strategy guide):

```kotlin
override fun onCreateView(
        inflater: LayoutInflater,
        container: ViewGroup?,
        savedInstanceState: Bundle?
): View {
	return ComposeView(requireContext()).apply {
		setViewCompositionStrategy(ViewCompositionStrategy.DisposeOnViewTreeLifecycleDestroyed)
		setContent {
			LoginScreen()
		}
	}
}
```

Assuming `LoginScreen` works as expected here, this would work until I went to run the test: we'd get a failure from Espresso as it wouldn't be able to find any view with the text "Login" as content contained in a `AndroidComposeView` isn't visible to Espresso's matchers. 

As far as I can tell if you're going to add Compose to an existing app that uses Espresso tests you need to either replace your Espresso code with `UIAutomator` for portions of tests that interact with Composables or only ever migrate whole flows  at a time so their UI testing can be migrated to `ComposeTestRule` (potentially infeasible for a lot of apps). Am I correct? And if so, are there plans to make Espresso support `AndroidComposeView` or to introduce new implementation agnostic test tooling? Either way, it feels to me like the [migration strategy docs](https://developer.android.com/develop/ui/compose/migrate/strategy) should be updated to highlight these constraints.
