### ISSUE TITLE
Remove Effect

### ISSUE THREAD

**Issue by tmxdyf** [android/compose-samples#1001]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is this a feature request for one of the samples?

- [X] Yes, this is a specific request related to this samples repo.

### Sample app

Other (bug not related to sample app)

### Describe the problem

Dear Compose developer, I am an ink screen（similar to kindle） APP developer, I hope that the click effect can be removed globally,Because it affects refresh performance, I hope to get your help.

### Describe the solution

Remove Effect via Theme?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by riggaroo** [comment]
Hi! 

This issue seems unrelated to the `compose-samples` repository directly, issues here are reserved for bug reports within the `compose-samples` apps or feature requests for the sample apps. 

For questions related to Jetpack Compose - we recommend asking them on [StackOverflow](https://stackoverflow.com/questions/ask?tags=android-jetpack-compose) with the `android-jetpack-compose` tag. 

If you find an issue with an Android Jetpack Compose components, report it using the [Jetpack Compose issue tracker](https://issuetracker.google.com/issues/new?component=612128&template=1253476).
