### ISSUE TITLE
[Jetsnack]: Navigate case LazyColumn last element partially visible.

### ISSUE THREAD

**Issue by CarefulDeveloper** [android/compose-samples#1137]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### Is this an issue related to one of the samples?

- [X] Yes, this is a specific issue related to this samples repo.

### Sample app

Jetsnack

### What happened?

1. Scroll a LazyColumn to bottom. 
2. Click on any element in the LazyColumn. It navigate me to the detail page. 
3. Press back button, it back to the LazyColumn page but not at bottom position. The last element in LazyCoumn is partially visible, I expect it is fully visible.

here's my bug reproduction screen recording.

https://github.com/android/compose-samples/assets/78646351/1bca7436-0afb-4b07-9aa7-9bae3aa6e7a8

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ibrahemid** [comment]
Hello @JolandaVerhoef, would it be alright if I create a pull request for this issue?

**Comment by JolandaVerhoef** [comment]
@ibrahemid yes, that would be wonderful!

**Comment by deepdelvadiya** [comment]
i thought lazy list by default saved the scroll position

**Comment by deepdelvadiya** [comment]
i have found the issue when navigate to detail screen shouldShowBottomBar is return false and cause reCompostion when navigate back to Feed screen shouldShowBottomBar return true and cause reCompostion and LazyColume shows the last item  partially. to solve this issue i have created viewModel and saves the scrollPostion into the ViModel's state variable and asign this variable to LazyListState's initialFirstVisibleItemIndex but still the issue is still persist

**Comment by rool78** [comment]
#1149
