### ISSUE TITLE
Question about dependecies

### ISSUE THREAD

**Issue by Zingam** [android/compose-samples#120]
Could you please explain why do we need all of these:

```
tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinCompile).configureEach {
    kotlinOptions {
        jvmTarget = "1.8"
        freeCompilerArgs += ["-Xallow-jvm-ir-dependencies", "-Xskip-prerelease-check"]
    }
}
```

How about just:

```
android {
    buildFeatures {
        compose true
    }
}
```
or nothing at all and be done with it? That's too much boilerplate!

**Comment by turastory** [comment]
Those compiler arguments are required in order to use Compose. You can find full list of jvm compiler arguments [here](https://github.com/JetBrains/kotlin/blob/master/compiler/cli/cli-common/src/org/jetbrains/kotlin/cli/common/arguments/K2JVMCompilerArguments.kt).

- `allow-jvm-ir-dependencies`
   This option suppress errors on using dependencies that were compiled by IR backend.
- `skip-prerelease-check`
   This option suppress errors on using classes that are not yet released.

So It seems like these two options are concerned with current states of Kotlin.

**Comment by JoseAlcerreca** [comment]
These are alpha flags. It's complicated because we're using Kotlin 1.4 and 1.3 at the same time. Obviously they will go away.
