### ISSUE TITLE
[BUG]:In a dual-core CPU machine, running Compose is very slow.

### ISSUE THREAD

**Issue by tmxdyf** [android/compose-samples#1245]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### Is this an issue related to one of the samples?

- [X] Yes, this is a specific issue related to this samples repo.

### Sample app

Other (bug not related to sample app)

### What happened?

In a dual-core CPU machine, when running Compose, the cold start is very slow. I hope you can provide a way to load it in /system/etc/preloaded-classes.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by riggaroo** [comment]
Hi! 

This issue seems unrelated to the `compose-samples` repository directly, issues here are reserved for bug reports within the `compose-samples` apps or feature requests for the sample apps. 

For questions related to Jetpack Compose - we recommend asking them on [StackOverflow](https://stackoverflow.com/questions/ask?tags=android-jetpack-compose) with the `android-jetpack-compose` tag. 

If you find an issue with an Android Jetpack Compose components, report it using the [Jetpack Compose issue tracker](https://issuetracker.google.com/issues/new?component=612128&template=1253476).
