### ISSUE TITLE
Import Typo in Compose docs

### ISSUE THREAD

**Issue by s4cha** [android/compose-samples#412]
Hello guys, I am happily migrating our app to compose beta1 (big fan of what you did there!), and
wanted to report a typo in the recent docs.

I got blocked trying to get `androidx.lifecycle:lifecycle-viewmodel.compose:1.0.0-alpha01` dependency to make `viewModel()` work again. as described here :

[https://developer.android.com/jetpack/androidx/releases/compose-ui](https://developer.android.com/jetpack/androidx/releases/compose-ui)

I tried in a fresh project etc but nothing worked, after 2 hours pulling my hair I figured I'd look into the samples and I found its actually :

`viewmodel-compose` and not `viewmodel.compose`.
If you could forward the report so they fix the typo I'm sure this would save time for many people migrating :)

Cheers!

**Comment by JoseAlcerreca** [comment]
Yes, the typo was already fixed in the codebase but it slipped into the release notes. We've sent a request to modify it manually (it's an automatic process). Thanks. Closing this as it's not an issue with the samples. Future non-sample issues can be filed in https://issuetracker.google.com/issues/new?component=610764&template=1424126
