### ISSUE TITLE
how can i make Text content center vertical

### ISSUE THREAD

**Issue by gfzy9876** [android/compose-samples#422]
i make Text a exact height
```kotlin
Text(
    text = "hahha",
    modifier = Modifier.height(200.dp),
    textAlign = TextAlign.Center
)
```
but it just content center horizontal, how can i make content center vertical like this in xml:

```xml
<TextView
    android:layout_width: "match_parent"
    android:layout_height: "200dp" 
    android:layout_gravity: "center"/>
```

i know a way to make content center horizontal is:

```kotlin
Card(
    modifier = Modifier
    .heightIn(200.dp)
) {
    Box(
    contentAlignment = Alignment.Center
) {
    Text(text = "$it", modifier = Modifier)
  }
}
```

but is not what i wanted

i wanna is there a way of making content center vertical like in xmls,thank U

**Comment by nickbutcher** [comment]
Use the `.wrapContentHeight()` modifier which accepts an `Alignment` param to center the text within its container. Closing as not an issue with the samples—this kind of question is better for StackOverflow.

**Comment by rayarteagas** [comment]
When writing custom layouts TextAlign is pretty handy, as we can place the text at 0,0 with parent width/height as maxWidth/maxHeight, and Text will handle the horizontal alignment for us. 

In case of the vertical alignment, when using the .wrapContentHeight() approach, It forces us to use a SubcomposeLayout to measure the text in order to place it correctly at its parent. I personally think that adding VerticalAlignment to text will add consistency to the framework and help solving problems like this.
