### ISSUE TITLE
TextDelegate still not supported for Compose

### ISSUE THREAD

**Issue by MurilloMaciel** [android/compose-samples#661]
I'm having troubles trying to change dynamically some texts of my json animation.
In old ways, with View, we had TextDelegate to handle this problem, but for Lottie in JetPack Compose we still doesn't.

**Comment by riggaroo** [comment]
Hi! 

This issue seems unrelated to the `compose-samples` repository directly, issues here are reserved for bug reports within the `compose-samples` apps or feature requests for the sample apps. 

For questions related to Jetpack Compose - we recommend asking them on [StackOverflow](https://stackoverflow.com/questions/ask?tags=android-jetpack-compose) with the `android-jetpack-compose` tag. 

If you find an issue or have a feature request with an Android Jetpack Compose components, report it using the [Jetpack Compose issue tracker](https://issuetracker.google.com/issues/new?component=612128&template=1253476).
