### ISSUE TITLE
Favorites Feature

### ISSUE THREAD

**Issue by pandubaraja** [android/compose-samples#69]
Hello 👋,

I open this issue because I want to implement the Favorite Feature in Article Screen, I will open PR asap. 
Hope you guys have a good day and stay safe and healthy 🙏 

Thanks

![rsz_screenshot_1585967111](https://user-images.githubusercontent.com/30037407/78416976-a9218500-7657-11ea-9e90-42d0698d3618.png)

**Comment by JoseAlcerreca** [comment]
Hi there! Thanks very much for your interest.

This sample is a work in progress and we need to make sure it actually makes sense to implement that feature (does it add anything new to the app that we want to showcase?). I don't think it would be interesting right now because we already have the similar bookmark feature.

**Comment by pandubaraja** [comment]
Hi @JoseAlcerreca , Okay no problem 😁, I thought someone need to impl it because there was a toast that show to replace it in the future when we clicked on that icon.
