### ISSUE TITLE
[Jetchat] Scroll position jumps on data updates

### ISSUE THREAD

**Issue by fwh-dc** [android/compose-samples#696]
Hi

JetChat seems to lack support for the following use case:
When the user has scrolled to any given position in the chat history and receives a new message the scroll position should be preserved. 

Currently the chat history jumps to more recent messages each time the list of messages changes.

This can be tested by 
1. Removing this line
https://github.com/android/compose-samples/blob/73a4e0d40d20e6a17d54cc9c6b7771a9f95ff17b/Jetchat/app/src/main/java/com/example/compose/jetchat/conversation/Conversation.kt#L128
2. Swipe up in the chat history
3. Type some messages

Please let me know if there is any way to achieve the desired functionality.

**Comment by jasonsaruulo** [comment]
If I understood you correctly, you want to stay at the position you scrolled to when the input text gains focus? I think you can do so by changing the `onTextFieldFocused` field of `UserInputText`. If you remove the `resetScroll()` from it, the scrolling position should remain the same when the input text gains focus.

https://github.com/android/compose-samples/blob/73a4e0d40d20e6a17d54cc9c6b7771a9f95ff17b/Jetchat/app/src/main/java/com/example/compose/jetchat/conversation/UserInput.kt#L144-L150

Does this help? I am not sure whether this is what you are trying to achieve as it is not receiving any new message.

**Comment by fwh-dc** [comment]
That is not what I am pointing at.

I am trying to show what happens to the scroll state if I remove resetScroll() completely. In an attempt to show what would happen if another Jetchat client texted me. Thereby changing the list of messages.

Here is a video were I have removed resetScroll() and I am sending messages. Look at how the view jumps each time a new message is received.

https://user-images.githubusercontent.com/56966127/142153670-08b6f526-9948-418a-b294-76cafe8f2a0c.mov

**Comment by jasonsaruulo** [comment]
The "jump" is because new messages are added to the bottom. Strictly seen, the scroll position is retained when a new message is added (y coordinate wise) but as a new message pushes up all the other items, there is this "jump".

I am not sure how `LazyColumn` works in detail but here might be a way to achieve your desired behavior.

1. In `Conversation.kt`, initialise the `LazyColumn` with `reverseLayout = false`.
2. In `ConversationUiState.kt`, add to the end of the list, not to the beginning `_messages.add(msg)`.
3. In `UserInput.kt`, remove `resetScroll()` from `onMessageSent` declaration.

The example data will be in reversed order but if you use your own data, it should be fine.

I like to mention that some messaging applications jump automatically to the bottom when sending a message. If your application behaves differently, it might confuse the users. :P

**Comment by fwh-dc** [comment]
I was able to solve the jump issue in our chat application by setting "key = { it.id }" when using items() in LazyColumn. That way Compose know how to position it self on updates to the message list. Perhaps that could be added to this example?

> I like to mention that some messaging applications jump automatically to the bottom when sending a message. If your application behaves differently, it might confuse the users. :P

Agree but I had to hack Jetchat to test this use case.
