### ISSUE TITLE
Bottom sheet covers bottom navigation bar, how to open it from behind

### ISSUE THREAD

**Issue by thrlr123** [android/compose-samples#702]
I am using BottomSheetScaffold with Scaffold that has BottomBar and when the bottomsheet is opened, it opens on top/front of bottom navigation bar, covering it instead of opening from behind. Is there any way to achieve this? Also, is there a way to anchor the bottom sheet to different points on screen instead of only Expand(full height) and Collapse(all the way down)?

**Comment by riggaroo** [comment]
Hi! 

This issue seems unrelated to the `compose-samples` repository directly, issues here are reserved for bug reports within the `compose-samples` apps or feature requests for the sample apps. 

For questions related to Jetpack Compose - we recommend asking them on [StackOverflow](https://stackoverflow.com/questions/ask?tags=android-jetpack-compose) with the `android-jetpack-compose` tag. 

If you find an issue with an Android Jetpack Compose components, report it using the [Jetpack Compose issue tracker](https://issuetracker.google.com/issues/new?component=612128&template=1253476).
