### ISSUE TITLE
WebView scrolling issue in ModelDrawer and Scaffold

### ISSUE THREAD

**Issue by prashantgoyal301** [android/compose-samples#738]
when we have used webview and any other third party lib in which they have their own gestures 
and put it on Model Drawer and Scaffold then it does not work.

**Comment by Amagi82** [comment]
I ran into the same issue and ended up disabling drawer gestures when the drawer was closed, e.g. `drawerGesturesEnabled = !scaffoldState.drawerState.isClosed`, and relying on the menu buttons to open it. The open gesture kinda conflicts with the gesture back buttons anyway. Not a perfect solution, but better than nothing.

**Comment by riggaroo** [comment]
Hi! 

This issue seems unrelated to the `compose-samples` repository directly, issues here are reserved for bug reports within the `compose-samples` apps or feature requests for the sample apps. 

For questions related to Jetpack Compose - we recommend asking them on [StackOverflow](https://stackoverflow.com/questions/ask?tags=android-jetpack-compose) with the `android-jetpack-compose` tag. 

If you find an issue with an Android Jetpack Compose components, report it using the [Jetpack Compose issue tracker](https://issuetracker.google.com/issues/new?component=612128&template=1253476).
