### ISSUE TITLE
Disabling copy/paste for TextField is not working.

### ISSUE THREAD

**Issue by suhailali** [android/compose-samples#753]
Disabling long press on TextField is not working. Is there any way block copy/paste.

**Comment by riggaroo** [comment]
Hi! 

This issue seems unrelated to the `compose-samples` repository directly, issues here are reserved for bug reports within the `compose-samples` apps or feature requests for the sample apps. 

For questions related to Jetpack Compose - we recommend asking them on [StackOverflow](https://stackoverflow.com/questions/ask?tags=android-jetpack-compose) with the `android-jetpack-compose` tag. 

If you find an issue with an Android Jetpack Compose components, report it using the [Jetpack Compose issue tracker](https://issuetracker.google.com/issues/new?component=612128&template=1253476).
