### ISSUE TITLE
LazyX issue with ContentPadding

### ISSUE THREAD

**Issue by Diegop88** [android/compose-samples#756]
When using LazyRow or LazyColumn, set a ContentPadding and set to each item `fillMaxParentWidth` for `LazyRow` or `fillMaxParentHeight` for `LazyColumn` will add the ContentPadding size to the item like `padding` modifier, and next item shows up on the screen

**Comment by Diegop88** [comment]
<img src="https://user-images.githubusercontent.com/8069737/158909286-67c13605-b1a9-4a39-a107-c15267596693.png" width=350 />

**Comment by riggaroo** [comment]
Hi! 

This issue seems unrelated to the `compose-samples` repository directly, issues here are reserved for bug reports within the `compose-samples` apps or feature requests for the sample apps. 

For questions related to Jetpack Compose - we recommend asking them on [StackOverflow](https://stackoverflow.com/questions/ask?tags=android-jetpack-compose) with the `android-jetpack-compose` tag. 

If you find an issue with an Android Jetpack Compose components, report it using the [Jetpack Compose issue tracker](https://issuetracker.google.com/issues/new?component=612128&template=1253476).
