### ISSUE TITLE
Use of kotlin.Result in JetNews

### ISSUE THREAD

**Issue by LeMimit** [android/compose-samples#768]
I was looking at the code of JetNews and I saw the use of a custom class `Result` instead of the native solution `kotlin.Result`.
https://github.com/android/compose-samples/blob/7132d1483676d07874f56d2bd18bd07d3212dd84/JetNews/app/src/main/java/com/example/jetnews/data/Result.kt#L22-L25

From my understanding, it is always better to use native solution (faster performance/support). Plus, the 
`kotlin.Result` comes with a lot of cool function like `runCatching`.

Why do you prefer using this custom class ? Is the official `kotlin.Result` bugged and not recommended to use in an Android project ?

It would be really interresting to have guidance on it in the documentation, if the use of `kotlin.Result` is not recommanded.

Like in this article https://developer.android.com/jetpack/guide/ui-layer/events#other-use-cases, where it is not recommanded to use Kotlin Channels to send actions from the ViewModel to the view.

Thanks a lot.

**Comment by alexvanyo** [comment]
The shortest answer is that I believe that code was written well before `kotlin.Result` was stable, so I wouldn't read into that as a recommendation against it. If you like how `kotlin.Result` works, go ahead and use it! I will point out one "gotcha" with `runCatching` since you mentioned it, which is that it will catch `CancellationException`s and therefore can mess up structured concurrency if you're not careful: https://github.com/Kotlin/kotlinx.coroutines/issues/1814
