### ISSUE TITLE
[Bug]: There is no executable file in the Rally project file and cannot be run

### ISSUE THREAD

**Issue by BraveHL** [android/compose-samples#848]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### Is this an issue related to one of the samples?

- [X] Yes, this is a specific issue related to this samples repo.

### Sample app

Rally

### What happened?

A bug happened!

There is no executable file in the Rally project file and cannot be run, so why put it in this project? 
Did not even give a separate GitHub address, the corresponding address in the project description is inaccessible in China, please add a GitHub address, this is related to millions of developers

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by BraveHL** [comment]
![image](https://user-images.githubusercontent.com/22335503/174008259-3c12612d-9b8c-40c8-ae71-a9f418ba3c33.png)

**Comment by BraveHL** [comment]
And here, I suggest adding https://developer.android.google.cn/jetpack/compose.
![image](https://user-images.githubusercontent.com/22335503/174009578-b5dc2f04-3961-445c-b994-1a57ea1106e4.png)

**Comment by IanGClifton** [comment]
The rally sample was removed from the repo but the readme with screenshots was kept because the sample is used in the navigation and testing codelabs. Maybe this causes more confusion than benefit? I'll chat with the team to see what we can do.

For the link, we can only have one in the about section for the whole repository unfortunately, so that just points to the main documentation that most developers will be able to access. There's also no way to change it based on user location as far as I know.
