### ISSUE TITLE
[Reply]: landscape navigation on a phone

### ISSUE THREAD

**Issue by Kernald** [android/compose-samples#921]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### Is this an issue related to one of the samples?

- [X] Yes, this is a specific issue related to this samples repo.

### Sample app

Reply

### What happened?

When running on a phone (Pixel 6 Pro) in landscape, Reply uses what looks like a permanent navigation drawer, with a button to collapse it. The button doesn't seem to be doing anything.

I'm actually curious what the proper navigation component would be for a phone in landscape.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Gurupreet** [comment]
Hi, Navigation component should be decided on the basis of device's actual available width using the WindowSizeClass instead of targeting static states like Mobile in landscape.
You can read more about it here https://goo.gle/compose-adaptive-codelab where it covers all navigation components with respect to window size.


Thanks for raising the bug it's being fixed here : #923

**Comment by Kernald** [comment]
I understand that the decision is based on the window size classes, but I question the choice of a persistent drawer on a phone, even in landscape. On a Pixel 6 Pro, that's taking almost half of the screen for navigation:

![Screenshot_20220810-231651.png](https://user-images.githubusercontent.com/296840/183911064-afe184b6-d3c1-44ae-adbf-dc5479b1d4d0.png)

The M3 spec sadly doesn't mention landscape in [here](https://m3.material.io/foundations/adaptive-design/large-screens/component-adaptation), which in itself is a bit weird when the focus of the page is to deal with multiple screen sizes and orientations. Is there a reference in the M3 spec that covers this?

**Comment by Gurupreet** [comment]
Hi @Kernald that's a known issue as Permanent navigation drawer had fixed static width which shouldn't be the case. It will be fixed in material3 alpha-17 update where navigation will have minimum width.

M3 guidance for [Canonical layouts ](https://m3.material.io/foundations/adaptive-design/canonical-layouts) may help you understand how window size can be used regardless of portrait or landscape mode.
