### ISSUE TITLE
[Bug]:  text color of textfield in dark theme has issue

### ISSUE THREAD

**Issue by razaghimahdi** [android/compose-samples#922]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### Is this an issue related to one of the samples?

- [X] Yes, this is a specific issue related to this samples repo.

### Sample app

Other (bug not related to sample app)

### What happened?

so I try to use textfield in my project, a textfield with custom colors, everything is ok in light theme, but when i active the dark theme, text color of textfield gets white, which I already defined as black, here a sample code:
```kotlin
TextField(
                                modifier = Modifier.fillMaxWidth(),
                                keyboardOptions = KeyboardOptions(
                                    keyboardType = KeyboardType.Text,
                                    imeAction = ImeAction.Default,
                                ),
                                value = state.description,
                                onValueChange = { 
                                        events(AddEvents.OnUpdateDescription(it)) 
                                },
                                shape = RoundedCornerShape(8.dp),
                                maxLines = 2,
                                colors = TextFieldThemeWithWhiteStyleForPrimaryBackground(),
                            )

@Composable
fun TextFieldThemeWithWhiteStyleForPrimaryBackground() = TextFieldDefaults.textFieldColors(
    backgroundColor = grey_050,
    cursorColor = Color.Black,
    textColor = Color.Black,
    disabledLabelColor = getMyShopThemeColor().background,
    focusedIndicatorColor = Color.Transparent,
    unfocusedIndicatorColor = Color.Transparent
)

```
I even put textfield in surface, and nothing changed

do u have any idea why all of this happening?
I even tried newest version: 1.2.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bentrengrove** [comment]
Hi! 

This issue seems unrelated to the `compose-samples` repository directly, issues here are reserved for bug reports within the `compose-samples` apps or feature requests for the sample apps. 

For questions related to Jetpack Compose - we recommend asking them on [StackOverflow](https://stackoverflow.com/questions/ask?tags=android-jetpack-compose) with the `android-jetpack-compose` tag. 

If you find an issue with an Android Jetpack Compose components, report it using the [Jetpack Compose issue tracker](https://issuetracker.google.com/issues/new?component=612128&template=1253476).

**Comment by razaghimahdi** [comment]
I thought maybe there is a bug in compose, but ok i'll do that, tnx
